site_name: Netherlands3D
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
nav:
  - 'index.md'
  - 'Beginnen met Netherlands3D':
      - 'installatie.md'
      - 'opzetten.md'
      - 'TileSystemGebruiken.md'
      - 'DataKlaarzetten.md'
      - 'gebieddsspecificatie.md'
  - 'basisproject.md'
  - 'Packages':
    - 'BAG.md'
    - 'Camera.md'
    - 'SelectionTools.md'
    - 'WMSLagen.md'
    - 'Zonnestand.md'
  - 'Packages':
    - 'packages/creating-and-managing-packages.md'
