site_name: Netherlands3D
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - 'index.md'
  - 'Beginnen met ..':
      - 'Beginnen.md'
      - 'TileSystemGebruiken.md'
      - 'DataKlaarzetten.md'
      - 'DataKoppelen.md'
  - 'Features':
    - 'Embedding.md'
    - 'BAG.md'
    - 'Camera.md'
    - 'SelectionTools.md'
    - 'WMSLagen.md'
    - 'Zonnestand.md'
  - 'Packages':
    - 'packages/creating-and-managing-packages.md'
