site_name: Netherlands3D
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.instant
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - 'index.md'
  - 'Beginnen met ..':
      - 'Beginnen.md'
      - 'TileSystemGebruiken.md'
      - 'DataKlaarzetten.md'
      - 'DataKoppelen.md'
  - 'Features':
    - 'Embedding.md'
    - 'BAG.md'
    - 'Camera.md'
#    - 'SelectionTools.md'
#    - 'WMSLagen.md'
#    - 'Zonnestand.md'
  - 'Packages':
    - 'packages/creating-and-managing-packages.md'
  - 'User interface':
    - 'ui/introduction.md'
    - 'ui/keeping-our-documentation-current.md'
    - 'ui/understanding-blocks.md'
    - 'ui/understanding-components.md'
    - 'Blocks':
      - 'ui/blocks/property-panel-and-sections.md'
    - 'Components':
      - 'ui/components/cards.md'
      - 'ui/components/sliders.md'
      - 'ui/components/text-fields.md'
