site_name: Netherlands3D
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.path
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - 'index.md'
#  - 'Eindgebruikers':
  - 'Voor ontwikkelaars':
    - 'developers/basis-in-een-uur.md'
    - 'Beginnen.md'
    - 'TileSystemGebruiken.md'
    - 'DataKlaarzetten.md'
    - 'DataKoppelen.md'
    - 'Features':
        - 'Embedding.md'
        - 'BAG.md'
        - 'Camera.md'
        - 'Layers.md'
    - 'Packages':
        - 'developers/packages/creating-and-managing-packages.md'
    - 'User interface':
      - 'developers/ui/introduction.md'
      - 'developers/ui/keeping-our-documentation-current.md'
      - 'developers/ui/understanding-blocks.md'
      - 'developers/ui/understanding-components.md'
      - 'Blocks':
        - 'developers/ui/blocks/property-panel-and-sections.md'
      - 'Components':
        - 'developers/ui/components/accordion.md'
        - 'developers/ui/components/cards.md'
        - 'developers/ui/components/sliders.md'
        - 'developers/ui/components/double-sliders.md'
        - 'developers/ui/components/text-fields.md'
